language: python
python:
  - "3.7"
  - "3.7.1"

before_install:
  - python --version

script: 
  - conda create -n fenicsproject -c conda-forge fenics
  - source activate fenicsproject
  - make project
  - make build  

