language: python

python:
  - "3.7"

before_install:
  - python --version

script: 
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH # the path given for default miniconda install is wrong, PATH=/home/travis/miniconda/bin:$PATH == X
  - conda update --yes conda 
  - make test
  - make project
  - make build  
  - pip3 install yfinance
  - make dynamic
  # - ./start_server.sh 

