language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
cache: pip
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
install: pip install -e .
script: pytest # this currently works on travisci , edit this after testing on circleci

